version: "2"
services:
  elasticsearch:
    container_name: elasticsearch
    build: .
    restart: always
    network_mode: bridge
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
volumes:
  data:
    driver: local
