version: "2"
services:
  redis:
    image: redis
    container_name: redis
    restart: always
    network_mode: bridge
    volumes:
      - data:/data
    ports:
      - "127.0.0.1:6379:6379"
volumes:
  data:
    driver: local
